version: '3'
services:
  flask_app:
    container_name: Jc-Jumper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - /root/Jc-Jumper:/app
    restart: unless-stopped
